sudo: required
language: ruby

rvm:
  - 2.3
  - 2.2
  - 2.1

before_install:
  - sudo apt-get update
  - sudo apt-get install libgeoip-dev
  - gem update bundler

gemfile:
  - Gemfile
  - gemfiles/fluentd_v0.10.gemfile
  - gemfiles/fluentd_v0.12.gemfile

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/fluentd_v0.10.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/fluentd_v0.10.gemfile
  allow_failures:
    - gemfile: gemfiles/fluentd_v0.10.gemfile
    - rvm: 1.9.3
    - rvm: 2.0.0
